userTags:
  - Translated by
  - Read by
  - Checked by
  - Corrections by
  - Edited by

stateTags:
  - Translation
  - Editing

additionalTags:
  - Comment

requiredTags:
  - Translation
  - Translated by

tagValues:
  - Finished
  - Partial
  - Demo-only
  - Unknown

contributorsIndex:
  mewo: ~à¸…^â€¢ï»Œâ€¢^à¸…~#2706 (Mewo)
  panaxyn: FirstTroph#9096 (panaxyn)
  lugi: Lugitaro ğŸ‰#0893
  lemonjuice: Lemonjuice#4631
  bobbarberer: bobbarberer#7752
  percivical: Percival/Aaliyah#6004
  jasu: âœ¨ Jasuanti ğŸŒ¸#7924
  dagobert: Dagobert#5282
  function: Function#5603
  schako: Schackowski#5364
  haj: Haj#1217
  meta: ğŸŒˆ Meta#5256

extraFiles:
  - languages/en/XX_BERLYMOD.yaml # no belry mod
  - js/plugins/omori-german.js
  - img/system/splash-omori-german.png

omitFiles:
  - img/system/splash-omori-german.psd

noMetadataCheckFiles:
  - www-js/omori-german.js
  - img/system/splash-omori-german.png

bundleModsInKit:
  - no belry
  - canvasbgon
  - enabledbg
  - enablemouse
  - modhistory
  - runinbackground

# replacement: bannedString'
bannedStringsInYaml:
  Ã¤: "ÃƒÂ¤"
  Ã¶: "ÃƒÂ¶"
  Ã¼: "ÃƒÂ¼"
  Ã„: "ÃƒÂ„"
  Ã–: "ÃƒÂ–"
  Ãœ: "ÃƒÂœ"
  ÃŸ: "ÃƒÂŸ"